version: '3.1'

services:
  server:
    build:
      context: ./application
    container_name: aniflix-webserver
    restart: always
    ports:
      - 80:80
    volumes:
      - .appl/src:/var/www/html